---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yourusername/public_html
    - /bin/cp -r * $DEPLOYPATH/
    - /bin/cp -r .env.example $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan key:generate
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 755 storage
    - chmod -R 755 bootstrap/cache
