#!/bin/bash

echo "🔧 Interactive FTP Test for s040.host-age.ro"
echo "============================================="
echo ""
echo "Server FTP is working! ✅"
echo "Now we need your FTP credentials from cPanel."
echo ""
echo "📋 To get your FTP credentials:"
echo "1. Go to: https://s040.host-age.ro:2083"
echo "2. Login to cPanel"
echo "3. Go to 'FTP Accounts'"
echo "4. Find or create an FTP account"
echo "5. Note down:"
echo "   - Server: s040.host-age.ro"
echo "   - Username: [your_username]"
echo "   - Password: [your_password]"
echo ""
echo "Then run this command to test:"
echo "lftp -c \"set ftp:ssl-allow no; open s040.host-age.ro; user [username] [password]; ls; quit\""
echo ""
echo "Or test interactively:"
echo "lftp s040.host-age.ro"
echo "user [username] [password]"
echo "ls"
echo "quit"

