name: Deploy to cPanel via FTP Only

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, sqlite3
        coverage: none
        
    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction
      
    - name: Build assets (if using Vite)
      run: |
        npm ci
        npm run build
        
    - name: Create .env file for production
      run: |
        cp .env.example .env
        # Update production settings
        sed -i 's/APP_ENV=local/APP_ENV=production/' .env
        sed -i 's/APP_DEBUG=true/APP_DEBUG=false/' .env
        sed -i 's|APP_URL=http://lms.local:8000|APP_URL=https://self-learn.ro|' .env
        
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/self-learn.ro/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
          **/tests/**
          **/*.md
          **/*.sh
          **/*.mp4
          **/phpunit.xml
          **/.cpanel.yml
          **/.env.example
          
    - name: Generate application key via FTP
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        key: ${{ secrets.CPANEL_SSH_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.CPANEL_USERNAME }}/public_html/self-learn.ro
          
          # Set proper permissions
          chmod -R 755 storage
          chmod -R 755 bootstrap/cache
          
          # Generate application key
          php artisan key:generate
          
          # Run migrations
          php artisan migrate --force
          
          # Cache configuration
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
          echo "Deployment completed successfully!"
